# Generated by Django 4.0 on 2021-12-22 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(related_name='contributors', through='api.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
