# Generated by Django 4.0 on 2021-12-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, choices=[('CON', 'Contribotor'), ('AUTH', 'Author')], max_length=10, null=True),
        ),
    ]
