# Generated by Django 4.0 on 2021-12-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('CON', 'Contribotor'), ('AUTH', 'Author')], default='AUTH', max_length=10),
        ),
    ]
