# Generated by Django 4.0 on 2021-12-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_contributor_project_alter_contributor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.CharField(choices=[('BE', 'Backend'), ('FE', 'Frontend'), ('IOS', 'Ios'), ('AN', 'Android')], max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
