# Generated by Django 4.0 on 2021-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_project_label_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='tag',
        ),
        migrations.AddField(
            model_name='issue',
            name='balise',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMP', 'Improvement'), ('TASK', 'Task')], default='BUG', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('N', 'Normal'), ('L', 'Low')], max_length=10),
        ),
    ]
