# Generated by Django 4.0 on 2021-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_issue_tag_issue_balise_alter_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='balise',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMP', 'Improvement'), ('TASK', 'Task')], default='TASK', max_length=4),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('N', 'Normal'), ('L', 'Low')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('PRO', 'Processing'), ('TODO', 'To Do')], default='TODO', max_length=4),
        ),
    ]
